CREATE TABLE document_classification (
	number VARCHAR(10),
	n1 VARCHAR(10),
	n2 VARCHAR(10),
	n3 VARCHAR(10),
	type VARCHAR(1),
	name VARCHAR(250),
	current_phase VARCHAR(80),
	intermediate_phase VARCHAR(80),
	destination VARCHAR(80)
);

INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('000', '', '', '', 'S', 'ADMINISTRAÇÃO GERAL', '', '', '');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('001', '000', '', '', 'A', 'MODERNIZAÇÃO E REFORMA ADMINISTRATIVA PROJETOS, ESTUDOS E NORMAS', 'Enquanto vigora', '5 anos', 'Guarda permanente');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('002', '000', '', '', 'A', 'PLANOS, PROGRAMAS E PROJETOS DE TRABALHO', '5 anos', '9 anos', 'Guarda permanente');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('003', '000', '', '', 'A', 'RELATÓRIOS DE ATIVIDADES', '5 anos', '9 anos', 'Guarda permanente');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('004', '000', '', '', 'A', 'ACORDOS. AJUSTES. CONTRATOS. CONVÊNIOS', 'Enquanto vigora', '10 anos', 'Guarda permanente');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('010', '', '', '', 'A', 'ORGANIZAÇÃO E FUNCIONAMENTO NORMAS, REGULAMENTAÇÕES, DIRETRIZES, PROCEDI- MENTOS, ESTUDOS E/OU DECISÕES DE CARÁTER GERAL', 'Enquanto vigora', '5 anos', 'Guarda permanente');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('010.1', '010', '', '', 'S', 'REGISTRO NOS ÓRGÃOS COMPETENTES', 'Enquanto vigora', '', 'õ67°');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('010.2', '010', '', '', 'A', 'REGIMENTOS. REGULAMENTOS. ESTA- TUTOS. ORGANOGRAMAS. ESTRUTURAS', 'Enquanto vigora', '5 anos', 'Guarda permanente');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('010.3', '010', '', '', 'A', 'AUDIÊNCIAS. DESPACHOS. REUNIÕES', '2 anos', '', 'õ67°');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('011', '', '', '', 'A', 'COMISSÕES. CONSELHOS. GRUPOS DE TRABALHO. JUNTAS. COMITÊS', '4 anos', '5 anos', 'õ67°');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('011.1', '', '', '', 'A', 'ATOS DE CRIAÇÃO, ATAS, RELATÓRIOS', '4 anos', '5 anos', 'Guarda permanente');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('012', '', '', '', 'S', 'COMUNICAÇÃO SOCIAL', '', '', '');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('012.1', '012', '', '', 'A', 'RELAÇÕES COM A IMPRENSA', '1 ano', '', 'õ67°');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('012.11', '012', '012.1', '', 'A', 'CREDENCIAMENTO DE JORNALISTAS', 'Enquanto vigora', '', 'õ67°');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('012.12', '012', '012.1', '', 'A', 'ENTREVISTAS. NOTICIÁRIOS. REPORTAGENS. EDITORIAIS', '2 anos', '', 'õ67°');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('012.2', '012', '', '', 'A', 'DIVULGAÇÃO INTERNA', '2 anos', '', 'õ67°');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('012.3', '012', '', '', 'A', 'CAMPANHAS INSTITUCIONAIS. PUBLICIDADE', '4 anos', '10 anos', 'Guarda permanente');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('019', '', '', '', 'S', 'OUTROS ASSUNTOS REFERENTES À ORGANI- ZAÇÃO E FUNCIONAMENTO', '', '', '');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('019.1', '019', '', '', 'A', 'INFORMAÇÕES SOBRE O ÓRGÃO', '2 anos', '', 'õ67°');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('020', '', '', '', 'S', 'PESSOAL', '', '', '');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('020.1', '020', '', '', 'A', 'LEGISLAÇÃO - NORMAS, REGULAMENTAÇÕES, DIRETRIZES, ESTATUTOS, REGULAMENTOS, PROCEDIMENTOS, ESTUDOS E/OU DECISÕES DE CARÁTER GERAL', 'Enquanto vigora', '5 anos', 'Guarda permanente');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('020.11', '020', '020.1', '', 'A', 'BOLETINS  ADMINISTRATIVO,  DE  PESSOAL  E  DE SERVIÇO', '10 anos', '10 anos', 'Guarda permanente');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('020.2', '020', '', '', 'A', 'IDENTIFICAÇÃO FUNCIONAL (INCLUSIVE CARTEIRA, CARTÃO, CRACHÁ, CREDENCIAL E PASSAPORTE DIPLOMÁTICO)', 'Enquanto o servidor permanecer', '', 'õ67°');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('020.3', '020', '', '', 'A', 'OBRIGAÇÕES TRABALHISTAS E ESTA- TUTÁRIAS. RELAÇÕES COM ÓRGÃOS NORMATIZADORES DA ADMINISTRAÇÃO PÚBLICA. LEI DOS 2/3. RAIS', '5 anos', '5 anos', 'õ67°');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('020.31', '020', '020.3', '', 'A', 'RELAÇÕES COM OS CONSELHOS PROFISSIONAIS', '2 anos', '', 'õ67°');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('020.4', '020', '', '', 'A', 'SINDICATOS. ACORDOS. DISSÍDIOS', '5 anos', '5 anos', 'Guarda permanente');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('020.5', '020', '', '', 'A', 'ASSENTAMENTOS INDIVIDUAIS. CADASTRO', 'Enquanto o servidor permanecer', '?', 'õ67°');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('021', '', '', '', 'S', 'RECRUTAMENTO E SELEÇÃO', '', '', '');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('021.1', '021', '', '', 'A', 'CANDIDATOS A CARGO E EMPREGO PÚBLICOS: INSCRIÇÃO E CURRICULUM VITAE', '2 anos', '', 'õ67°');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('021.2', '021', '', '', 'A', 'EXAMES DE SELEÇÃO (CONCURSOS PÚBLICOS) PROVAS E TÍTULOS, TESTES PSICOTÉCNICOS E EXAMES MÉDICOS', '6 anos', '', 'õ67°');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('021.21', '021', '021.2', '', 'A', 'CONSTITUIÇÃO DE BANCAS EXAMINADORAS, EDITAIS, EXEMPLARES ÚNICOS DE PROVAS, GABARITOS, RESULTADOS E RECURSOS', '6 anos', '5 anos', 'Guarda permanente');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('022', '', '', '', 'S', 'APERFEIÇOAMENTO E TREINAMENTO', '', '', '');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('022.1', '022', '', '', 'A', 'CURSOS (INCLUSIVE BOLSAS DE ESTUDO)', '', '', '');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('022.11', '022', '022.1', '', 'A', 'PROMOVIDOS PELA INSTITUIÇÃO', '5 anos', '', 'õ67°');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('022.111', '022', '022.1', '022.11', 'A', 'PROPOSTAS, ESTUDOS, EDITAIS, PROGRAMAS, RELATÓRIOS FINAIS, EXEMPLARES ÚNICOS DE EXERCÍCIOS, RELAÇÃO DE PARTICIPANTES, AVALIAÇÃO E CONTROLE DE EXPEDIÇÃO DE CERTIFICADOS', '5 anos', '5 anos', 'Guarda permanente');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('022.12', '022', '022.1', '', 'A', 'PROMOVIDOS POR OUTRAS INSTITUIÇÕES', '', '', '');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('022.121', '022', '022.1', '022.12', 'A', 'NO BRASIL', '5 anos', '', 'õ67°');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('022.122', '022', '022.1', '022.12', 'A', 'NO EXTERIOR', '5 anos', '', 'õ67°');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('022.2', '022', '', '', 'A', 'ESTÁGIOS (INCLUSIVE BOLSAS DE ESTÁGIO)', '', '', '');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('022.21', '022', '022.2', '', 'A', 'PROMOVIDOS PELA INSTITUIÇÃO', '5 anos', '', 'õ67°');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('022.211', '022', '022.2', '022.21', 'A', 'ESTUDOS, PROPOSTAS, PROGRAMAS, RELATÓRIOS FINAIS, RELAÇÃO DE PARTICIPANTES, AVALIAÇÃO E DECLARAÇÃO DE COMPROVAÇÃO DE ESTÁGIO', '5 anos', '5 anos', 'Guarda permanente');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('022.22', '022', '022.2', '', 'A', 'PROMOVIDOS POR OUTRAS INSTITUIÇÕES', '', '', '');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('022.221', '022', '022.2', '022.22', 'A', 'NO BRASIL', '5 anos', '', 'õ67°');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('022.222', '022', '022.2', '022.22', 'A', 'NO EXTERIOR', '5 anos', '', 'õ67°');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('022.9', '022', '', '', 'A', 'OUTROS ASSUNTOS REFERENTES A APERFEIÇOAMENTO E TREINAMENTO', '', '', '');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('023', '', '', '', 'S', 'QUADROS, TABELAS E POLÍTICA DE PESSOAL', '', '', '');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('023.01', '023', '', '', 'A', 'ESTUDOS E PREVISÃO DE PESSOAL', '5 anos', '5 anos', 'Guarda permanente');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('023.02', '023', '', '', 'A', 'CRIAÇÃO, CLASSIFICAÇÃO, TRANSFOR- MAÇÃO, TRANSPOSIÇÃO E REMUNE- RAÇÃO DE CARGOS E FUNÇÕES', '5 anos', '5 anos', 'Guarda permanente');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('023.03', '023', '', '', 'A', 'REESTRUTURAÇÕES E ALTERAÇÕES SALARIAIS ASCENSÃO E PROGRESSÃO FUNCIONAL AVALIAÇÃO DE DESEMPENHO ENQUADRAMENTO EQUIPARAÇÃO, REAJUSTE E REPOSIÇÃO SALARIAL PROMOÇÕES', '5 anos', '47 anos', 'õ67°');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('023.1', '023', '', '', 'A', 'MOVIMENTAÇÃO DE PESSOAL', '', '', '');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('023.11', '023', '023.1', '', 'A', 'ADMISSÃO. APROVEITAMENTO. CONTRATAÇÃO. NOMEAÇÃO. READMISSÃO. READAPTAÇÃO. RECONDUÇÃO. REINTEGRAÇÃO. REVERSÃO', '5 anos', '47 anos', 'õ67°');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('023.12', '023', '023.1', '', 'A', 'DEMISSÃO.  DISPENSA. EXONERAÇÃO. RESCISÃO CONTRATUAL. FALECIMENTO', '5 anos', '47 anos', 'õ67°');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('023.13', '023', '023.1', '', 'A', 'LOTAÇÃO. REMOÇÃO. TRANSFERÊNCIA. PERMUTA', '4 anos', '5 anos', 'õ67°');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('023.14', '023', '023.1', '', 'A', 'DESIGNAÇÃO. DISPONIBILIDADE. REDISTRIBUIÇÃO. SUBSTITUIÇÃO', '5 anos', '47 anos', 'õ67°');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('023.15', '023', '023.1', '', 'A', 'REQUISIÇÃO. CESSÃO', '5 anos', '47 anos', 'õ67°');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('024', '', '', '', 'S', 'DIREITOS, OBRIGAÇÕES E VANTAGENS', '', '', '');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('024.1', '024', '', '', 'A', 'FOLHAS DE PAGAMENTO. FICHAS FINANCEIRAS', '5 anos', '95 anos', 'õ67°');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('024.11', '024', '024.1', '', 'A', 'SALÁRIOS, VENCIMENTOS, PROVENTOS E REMUNERAÇÕES', '7 anos', '', 'õ67°');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('024.111', '024', '024.1', '024.11', 'A', 'SALÁRIO-FAMÍLIA', '5 anos', '19 anos', 'õ67°');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('024.112', '024', '024.1', '024.11', 'A', 'ABONO OU PROVENTO PROVISÓRIO', '7 anos', '', 'õ67°');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('024.113', '024', '024.1', '024.11', 'A', 'ABONO DE PERMANÊNCIA EM SERVIÇO', 'Até a homologação da aposentadoria', '', 'õ67°');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('024.119', '024', '024.1', '024.11', 'A', 'OUTROS SALÁRIOS, VENCIMENTOS, PROVENTOS E REMUNERAÇÕES', '7 anos', '', 'õ67°');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('024.12', '024', '024.1', '', 'A', 'GRATIFICAÇÕES (INCLUSIVE INCORPORAÇÕES)', '', '', '');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('024.121', '024', '024.1', '024.12', 'A', 'DE FUNÇÃO', '5 anos', '47 anos', 'õ67°');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('024.122', '024', '024.1', '024.12', 'A', '>è', '7 anos', '', 'õ67°');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('024.123', '024', '024.1', '024.12', 'A', 'CARGOS EM COMISSÃO', '5 anos', '47 anos', 'õ67°');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('024.124', '024', '024.1', '024.12', 'A', 'NATALINAS (DÉCIMO TERCEIRO SALÁRIO)', '7 anos', '', 'õ67°');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('024.129', '024', '024.1', '024.12', 'A', 'OUTRAS GRATIFICAÇÕES', '5 anos', '47 anos', 'õ67°');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('024.13', '024', '024.1', '', 'A', '­,8z<', '', '', '');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('024.131', '024', '024.1', '024.13', 'A', 'TEMPO DE SERVIÇO (ANUÊNIOS, (BIÊNIOS E QÜINQÜÊNIOS)', '5 anos', '47 anos', 'õ67°');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('024.132', '024', '024.1', '024.13', 'A', 'NOTURNO', '5 anos', '47 anos', 'õ67°');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('024.133', '024', '024.1', '024.13', 'A', 'ÂÞhÒÚÞ', '5 anos', '47 anos', 'õ67°');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('024.134', '024', '024.1', '024.13', 'A', 'INSALUBRIDADE', '5 anos', '47 anos', 'õ67°');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('024.135', '024', '024.1', '024.13', 'A', 'ATIVIDADES PENOSAS', '5 anos', '47 anos', 'õ67°');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('024.136', '024', '024.1', '024.13', 'A', 'SERVIÇOS EXTRAORDINÁRIOS (HORAS EXTRAS)', '5 anos', '47 anos', 'õ67°');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('024.137', '024', '024.1', '024.13', 'A', 'FÉRIAS: ADICIONAL DE 1/3 E ABONO PECUNIÁRIO', '7 anos', '', 'õ67°');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('024.139', '024', '024.1', '024.13', 'A', 'OUTROS ADICIONAIS', '5 anos', '47 anos', 'õ67°');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('024.14', '024', '024.1', '', 'A', 'DESCONTOS', '', '', '');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('024.141', '024', '024.1', '024.14', 'A', 'CONTRIBUIÇÃO SINDICAL DO SERVIDOR', '7 anos', '', 'õ67°');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('024.142', '024', '024.1', '024.14', 'A', 'CONTRIBUIÇÃO PARA O PLANO DE SEGURIDADE SOCIAL', '5 anos', '47 anos', 'õ67°');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('024.143', '024', '024.1', '024.14', 'A', 'IMPOSTO DE RENDA RETIDO NA FONTE (IRRF)', '7 anos', '', 'õ67°');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('024.144', '024', '024.1', '024.14', 'A', 'PENSÕES ALIMENTÍCIAS', '5 anos', '95 anos', 'õ67°');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('024.145', '024', '024.1', '024.14', 'A', 'Ø0zü', '7 anos', '', 'õ67°');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('024.149', '024', '024.1', '024.14', 'A', 'OUTROS DESCONTOS', '7 anos', '', 'õ67°');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('024.15', '024', '024.1', '', 'A', 'ENCARGOS PATRONAIS. RECOLHIMEN- TOS', '', '', '');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('024.151', '024', '024.1', '024.15', 'A', 'PROGRAMA DE FORMAÇÃO DO PA- TRIMÔNIO DO SERVIDOR PÚBLICO (PASEP). PROGRAMA DE INTEGRA- ÇÃO SOCIAL (PIS)', '5 anos', '5 anos', 'õ67°');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('024.152', '024', '024.1', '024.15', 'A', 'FUNDO DE GARANTIA POR TEMPO DE SERVIÇO (FGTS)', '5 anos', '47 anos', 'õ67°');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('024.153', '024', '024.1', '024.15', 'A', 'CONTRIBUIÇÃO SINDICAL DO EMPREGADOR', '7 anos', '', 'õ67°');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('024.154', '024', '024.1', '024.15', 'A', 'CONTRIBUIÇÃO PARA O PLANO DE SEGURIDADE SOCIAL (INCLUSIVE CONTRIBUIÇÕES ANTERIORES)', '5 anos', '95 anos', 'õ67°');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('024.155', '024', '024.1', '024.15', 'A', 'SALÁRIO MATERNIDADE', '7 anos', '', 'õ67°');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('024.156', '024', '024.1', '024.15', 'A', 'IMPOSTO DE RENDA', '7 anos', '', 'õ67°');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('024.2', '024', '', '', 'A', 'Â¼', '7 anos', '', 'õ67°');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('024.3', '024', '', '', 'A', 'LICENÇAS - ACIDENTE EM SERVIÇO ADOTANTE - AFASTAMENTO DO CÔNJUGE/COMPANHEIRO ATIVIDADE POLÍTICA - CAPACITAÇÃO PROFISSIONAL DESEMPENHO DE MANDATO CLASSISTA DOENÇA EM PESSOA DA - AMÍLIA GESTANTE - PATERNIDADE - PRÊMIO POR ASSIDUIDADE SERVIÇO MILITAR -', '5 anos', '47 anos', 'õ67°');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('024.4', '024', '', '', 'A', 'AFASTAMENTOS - PARA DEPOR - PARA EXERCER MANDATO ELETIVO - PARA SERVIR AO TRIBUNAL REGIONAL ELEITORAL (TRE) - PARA SERVIR COMO JURADO - SUSPENSÃO DE CONTRATO DE TRABALHO (CLT)', '5 anos', '47 anos', 'õ67°');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('024.5', '024', '', '', 'A', 'REEMBOLSO DE DESPESAS', '', '', '');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('024.51', '024', '024.5', '', 'A', 'MUDANÇA DE DOMICÍLIO DE SERVIDORES', 'Até aprovação das contas', '5 anos a contar da  data de aprovação das contas', 'õ67°');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('024.52', '024', '024.5', '', 'A', 'LOCOMOÇÃO', 'Até aprovação das contas', '5 anos a contar da  data de aprovação das contas', 'õ67°');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('024.59', '024', '024.5', '', 'A', 'OUTROS REEMBOLSOS', 'Até aprovação das contas', '5 anos a contar da  data de aprova ão das contas', 'õ67°');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('024.9', '024', '', '', 'A', 'OUTROS DIREITOS, OBRIGAÇÕES E VANTAGENS', '', '', '');
INSERT INTO document_classification (number, n1, n2, n3, type, name, current_phase, intermediate_phase, destination) VALUES ('024.91', '024', '024.9', '', 'A', 'CONCESSÕES ALISTAMENTO ELEITORAL CASAMENTO (GALA) DOAÇÃO DE SANGUE - FALECIMENTO DE FAMILIARES (NOJO) - HORÁRIO  ESPECIAL  PARA  SERVIDOR ESTUDANTE - HORÁRIO  ESPECIAL  PARA  SERVIDOR - PORTADOR  DE DEFICIÊNCIA', '5 anos', '47 anos', 'õ67°');
